CREATE TABLE IF NOT EXISTS videos (
  id VARCHAR PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  title VARCHAR,
  suggested_title VARCHAR,
  real_path VARCHAR NOT NULL,
  static_path VARCHAR NOT NULL,
  bitrate INT,
  extra BOOL NOT NULL,
  processed BOOL NOT NULL,
  thumbnail_url VARCHAR,
  ts INT NOT NULL,
  pct_watched INT NOT NULL,
  finished BOOL NOT NULL,
  v_stream INT NOT NULL,
  a_stream INT NOT NULL,
  s_stream INT NOT NULL,
  s_pos INT NOT NULL,
  media_dir_id VARCHAR REFERENCES media_dirs(id) NOT NULL
);
